### PR TITLE
Create 970079.xyz.md

### PR DESCRIPTION
**Pull request by Wreeper**
Pingdom is bugged.
It takes useless things into consideration, my website only being 620B (https://cdn.discordapp.com/attachments/861229403429666846/894562868312309780/unknown.png)
while pingdom says it is 1.8kb.  You wanna know why it considers my website being weight at 1.8kb? Here you go: https://cdn.discordapp.com/attachments/861229403429666846/894563305023221790/unknown.png

My website has proper SSL redirection, it is secured. t0.vc has NO ssl redirection ,which means he won't load the content twice (but the content my website serves is being cached in https from http if you are redirected from unsecure to secure), which means it won't use mobile data twice. I am NOT removing the SSL redirection just for it to weigh the correct value as pingdom says, neither i am removing the SSL certificate (because yes, SSL certificates weigh).

However, t0.vc kinda has a changing value. Wanna know why? Because it's original weight is 1.1KB but Pingdom cannot handle that: https://cdn.discordapp.com/attachments/861229403429666846/894564070374666290/unknown.png

Pingdom isn't really a smart choice, because it thinks a 301 permanent redirect is actually loading the full website twice.

You may think that the domain is a spam domain - but the domain is a part of the 1.111B XYZ domain class: https://gen.xyz/1111b

### CODE REVIEW

**Comment by bradleytaunt** [comment]
To keep things on a clean and simple playing field, 1MB uses tools.pingdom

As such, your website should get rounded up to 1.0KB (as seen here: https://tools.pingdom.com/#5f13071813000000)

Once these changes are made I'll get everything merged in 😃

**Comment by Wreeper** [comment]
change t0.vc to 1kb too
https://tools.pingdom.com/#5f130d5ffec00000 (700B)

**Comment by Wreeper** [comment]
Done changed !

**Comment by bradleytaunt** [comment]
You don't need the `KB` in the size parameter and the size should be `1.0`

https://tools.pingdom.com/#5f13071813000000 `971.0B` --> second decimal place rounded == 1000 --> `1.0`

Not sure why it is set to `0.6`?

**Comment by Wreeper** [comment]
okay, changed to 1.0

**Comment by Wreeper** [comment]
Not sure why it is set to 0.6?

A: Because that's the actual website size, there's a reverse proxy acting and confusing pingdom

**Pull request merged**
