### PR TITLE
change of address matthewthom.as

### PR DESCRIPTION
**Pull request by mwt**
I finally got this new domain. This changes mattwthomas.com to matthewthom.as. I have a 301 redirect from the old domain.

https://gtmetrix.com/reports/www.matthewthom.as/UshNfnVP/

### CODE REVIEW

**Comment by bradleytaunt** [comment]
The file needs to be inside the `site_listings` directory

**Comment by mwt** [comment]
> The file needs to be inside the `site_listings` directory

Oops! This is fixed now.

**Comment by bradleytaunt** [comment]
Sorry, I also missed that you included the `www` - that is not needed 😃

**Comment by mwt** [comment]
Ok, I removed it. I had included to save a redirect. I use the www for CNAME cdn reasons.

**Pull request merged**
