### PR TITLE
Create leonardocosta.neocities.org.md

### PR DESCRIPTION
**Pull request by marginalia-digital**
Hello Bradley, hope you are well and safe. I apologize if I did something wrong with the project, but I tried to follow your guidelines to request permission to participate in the 1mb club. My site is simple, and it's more to make an online presence (since I don't use social media) than to "produce content". Thank you for your attention, and I await your reply. Congratulations on the initiative, and thank you very much for that. Hugs from Brazil. :)

### CODE REVIEW

**Comment by bradleytaunt** [comment]
Looks good! But you need to remove the `https://` from the pageurl parameter.

**Comment by bradleytaunt** [comment]
Sorry forgot to also mention: the `KB` text isn't needed in the `size` parameter

**Comment by marginalia-digital** [comment]
oh, Bradley!... I'm sorry about that! but I made the changes, and I think it's correct now! 
thank you so much for this!
:)

**Comment by bradleytaunt** [comment]
No problem - but one last thing 😛 

Your file name should just be the plain url with `.md` at the end. (No need to include the `http` etc.

So simply change:

`_site_listings/https:/leonardocosta.neocities.org.md`

to: 

`_site_listings/leonardocosta.neocities.org.md`

**Pull request merged**
