### PR TITLE
add more websites

### PR DESCRIPTION
**Pull request by maskmanlucifer**
add my website

### CODE REVIEW

**Comment by bradleytaunt** [comment]
I'm getting `143.2 KB` pretty consistently. (https://tools.pingdom.com/#5ea5a0337ec00000)

**Comment by maskmanlucifer** [comment]
Well that's strange coz i'm still getting at most 90 KB.
What i should do now ??.

**Comment by bradleytaunt** [comment]
It’s best to change it to what is stated on Pingdom (since that is the standard at which sites are added here)

**Comment by maskmanlucifer** [comment]
okk

**Pull request merged**
