### PR TITLE
Added https://lecaro.me/minimage/

### PR DESCRIPTION
**Pull request by renanlecaro**
This is a very lightweight web app to load an image, draw on it, then download the result. 
I don't know if you'll accept it is not a root url but a subfolder (it's a github page).
The app is open source, https://github.com/renanlecaro/minimage

### CODE REVIEW

**Comment by bradleytaunt** [comment]
A subpage is fine - but I am getting ~19.2KB whenever I test it through Pingdom FYI.

Maybe try retesting as well?

**Comment by renanlecaro** [comment]
Pingdom gives me a page size of 16.9kb
Firefox network inspector tells me he transferred 14.31 KB
Google chrome downloads the manifest and some high resolution favicons and reaches 21.0kb

There are some dynamic imports, the actual page size is 16.29 KB if you exclude manifest icons but include dynamic imports. 

Screenshots of the tools : 

pingdom
firefox
chrome

**Comment by bradleytaunt** [comment]
Still getting 19.1 KB --> https://tools.pingdom.com/#5e17fc553a800000

**Comment by renanlecaro** [comment]
Seems like it depends on the region ? I'm not sure but I don't mind, i've update the PR to say  19.1kb

**Pull request merged**
