### PR TITLE
added notes.whoibrar.com

### PR DESCRIPTION
**Pull request by whoibrar**

### CODE REVIEW

**Comment by bradleytaunt** [comment]
Your page size parameter is not set correctly ^

**Comment by whoibrar** [comment]
Hey @bradleytaunt !

As said in the ReadMe, 
1. I went ahead to pingdom website and entered the URL.
2. I got this screen (See blow Screenshot), I grab the page size and convert it to bytes.
3. Just to confirm, I check with another Website (Screenshot below) and find the same results.

P.S : This is my first time making a pull request, I guess I might've up something along the away. Would be happy to Learn what went wrong! Thanks! @bradleytaunt 

Screenshot - pingdom
Screenshot - Another Website

**Comment by bradleytaunt** [comment]
There is no need to convert to bytes. All sites listed simply use the KB listed via pingdom. Therefore you’re ‘size’ parameter should be 4.6

**Comment by whoibrar** [comment]
Oh, Now I get it! Thankyou @bradleytaunt for the info! 

I changed it to `size: 4.6`. I guess now it can be merged 🤞

**Pull request merged**
