### PR TITLE
added quitsocialmedia.club

### PR DESCRIPTION
**Pull request by xplosionmind**
- [landing page result](https://tools.pingdom.com/#5e0bf918d3c00000 "result for “https://quitsocialmedia.club”"): `226.0`KB
- [English homepage result](https://tools.pingdom.com/#5e0bf8b4b5800000 "result for “https://quitsocialmedia.club/home”"): `843.3`KB

### CODE REVIEW

**Comment by bradleytaunt** [comment]
You keep the domain the same (`quitsocialmedia.club`) but you should change the size to `843.3`. We shouldn't count the "splash screen" as an actual website.

**Comment by xplosionmind** [comment]
> We shouldn't count the "splash screen" as an actual website.

you’re right.

<br>

> you should change the size to `843.3`

Done!   
Thank you very much.

**Comment by bradleytaunt** [comment]
Sorry, also missed - your file needs to be a `markdown` file type.

**Comment by xplosionmind** [comment]
> your file needs to be a `markdown` file type

ah, you’re right again. I missed that too. Now fixed.   
Thanks again!

**Pull request merged**
