### PR TITLE
Added a bunch of my websites <1MB

### PR DESCRIPTION
**Pull request by raregems-io**

### CODE REVIEW

**Comment by raregems-io** [comment]
updated using gtmetrix

**Comment by bradleytaunt** [comment]
- 10xdev should be `0.9` https://tools.pingdom.com/#60c897a06fc00000
- nftrees.cc should be `598.0` https://tools.pingdom.com/#60c897dd27800000
- raregems.io should be `171.1`https://tools.pingdom.com/#60c89812a3400000
- soots.cc should be `619.5` https://tools.pingdom.com/#60c8984290c00000

**Comment by raregems-io** [comment]
I don't understand how pingdom measures the size of 10xdev.cc
gtmetrix shows that it's 392B compressed and 510B uncompressed.
where 0.9KB comes from?

Screenshot 2022-09-09 at 16 18 40

**Comment by bradleytaunt** [comment]
To keep things consistent with this project all sites are processed through Pingdom. Having different test suites will make site comparisons different.

Cheers

**Comment by raregems-io** [comment]
updated according to pingdom ✅

**Pull request merged**
